### ISSUE TITLE
Name of this module

### ISSUE THREAD

**Issue by mmaridev** [learnweb/moodle-mod_collabora#16]
Hi,

just a question: why is this module named as Collabora if not endorsed by them? I think it could be better to name it as LibreOffice Online which is the base product of Collabora Online and many others.
FYI i tested this plugin with LOOL 6.4 and works just fine.
I'm asking this rename just to indicate a wider compatibility of this module.

Thanks

**Comment by mwuttke** [comment]
Hello Marco,

you mean you tested this plugin against a LibreOffice Online Server, described here: https://wiki.documentfoundation.org/Development/BuildingOnline?
And it works! Great to hear!

Thanks & Greetings,
Michael

**Comment by mmaridev** [comment]
Yes, I'm the author of that page :-) and yes, it works fine.

**Comment by mwuttke** [comment]
Hello Marco,

oops! ;-)
Thanks for the great information. We will discuss the opportunity to rename this plugin.
Sorry for asking, but since when exists "LOOL" in this form?

And did you tested the other Moodle-Plugin (https://github.com/learnweb/moodle-assignsubmission_collabora) as well?

Thanks & Greetings,
Michael

**Comment by mmaridev** [comment]
Hi, LOOL always existed, is the base of Collabora Online. I'll test the other plugins as soon as possible but I think they'll work just fine.

**Comment by mmaridev** [comment]
I mean: a usable build of LOOL was missing and only TDFs partners as Collabora had them.

**Comment by mwuttke** [comment]
Hello Marco,

Thanks again for the information. If I compile the LOOL suit by my one, has it any limitations like CODE from Collabora Online?

Thanks & Greetings,
Michael

**Comment by mmaridev** [comment]
Hi, the limitations are due to two compilation flags:
`--with-max-connections=100000 --with-max-documents=100000` 
if you use something like this, it will have no limitation

**Comment by mwuttke** [comment]
Hello Marco,
ok! Thanks to you once again!
What do you think, if we mention your information in the README.md for now?
Michael

**Comment by mmaridev** [comment]
This would be a nice start :+1:

**Comment by mmaridev** [comment]
Actually, the main reason of this issue was at least to replace Collabora's Logo with TDF's one. If you don't want to do something like this, other connectors, e.g. the one in NextCloud, dynamically changes logos and texts accordingly to the backend server.
For the moment, I thank you so much for the modifications in the README.

**Comment by mmeeks** [comment]
> just a question: why is this module named as Collabora if not endorsed by them?

We provided assistance to help build it; and - as far as I know we promote it, endorse it, and are very happy to see it out there.

While Online re-uses the LibreOffice core, Collabora has done 95%+ of the commits to Online, and in order to sustain and improve the project it is extremely important that we generate leads & hence sales. As such the use of our brand is really appreciated.

The LibreOffice project is currently undergoing a wide ranging discussion of how it can change its practices to effectively credit those doing the investment (they currently do not) and try to work to address the horrible historic problems caused by its lack of reference / presentation of those contributing.

I write more about the background here: https://people.gnome.org/~michael/data/vendor-neutral-marketing.html

For my part I would recommend letting that LibreOffice discussion conclude in an equitable way before considering a rename.

**Comment by mwuttke** [comment]
Hello Michael,

thank you for your information and clarification. I will close the ticket with the reference to the elapsed discussion here:
https://github.com/owncloud/richdocuments/issues/277
and here:
https://github.com/nextcloud/richdocuments/issues/639.

Thanks & Greetings,
Michael

**Comment by mmaridev** [comment]
Dear @moodlebeuth ,

As @mmeeks pointed out, these discussions are not closed. See e.g. https://github.com/nextcloud/richdocuments/pull/941
TDF is currently working hard to reach a more vendor-neutral context near LibreOffice.
Calling this module "Collabora" excludes to who is not in the question the possibility that this module could work with all versions of LOOL and not only with the one shipped by Collabora.
From my point of view, forking this plugin and renaming it to "LibreOffice Online" would just result in double (4x considering the submission module) the work to maintain both modules where the code is exactly the same.
The goal is not to reinvent the wheel but to work together to have the best product possible.

Hope this will be helpful,
