### ISSUE TITLE
HTML entities aren't interpreted

### ISSUE THREAD

**Issue by abkoch** [learnweb/moodle-mod_collabora#39]
Dear developer,

just a tiny issue: HTML entities as &amp; aren't interpreted well in titles of activities:

https://i.postimg.cc/3xCCrwsY/Ampersand.jpg

Best regards
Andreas

**Comment by grabs** [comment]
Hi Andreas,

thanks for reporting this but it seems not to be related to the collabora plugin. The title is printed automatically together with the header of the page, which affects all activities. So I think, it must be fixed in moodle.

Best regards
Andreas

**Comment by abkoch** [comment]
Hi Andreas,

thanks for your response. The issue doesn't occur in e.g. in the activity "Page":

https://i.postimg.cc/ZYymj9NV/Page.jpg

That is why i assumed the issue is collabora-specific.

Best regards
Andreas

**Comment by grabs** [comment]
Hi Andreas,

sorry, you were right. I tested it with a wrong theme.
I now have changed the output and the meaning of that additional title a little.
Instead of the activity title the used filename is displayed. I also have optimized the instance configuration form to make this more clear.
The description now is correctly displayed in the new 4.x way.

Thank you and best regards
Andreas

**Comment by abkoch** [comment]
Hi Andreas,

great, thank you very much.

Best regards
Andreas
